Repository SauveJeanLuc/coffee-tasks, pull requests merged in 2022-10, with the labels that each got.

#17 issue #9, added a PR tempalte
  .github/pull_request_template.md
Labels: hacktoberfest-accepted

#26 eslint setup with some code fixes
  .eslintrc.cjs
  .github/workflows/eslint.yml
  package.json
  src/App.jsx
  src/components/PopUp.jsx
  src/components/atomic/Button.jsx
  src/components/atomic/Input.jsx
  src/components/atomic/SelectButton.jsx
Labels: hacktoberfest-accepted

#34 Fix typo
  index.html
Labels: hacktoberfest-accepted

#28 Updating Readme for Hacktoberfest contestants
  README.md
  contributing.md
Labels: hacktoberfest-accepted

#44 Added Tailwind Set-up to Project
  package.json
  postcss.config.cjs
  src/App.jsx
  src/components/Header.jsx
  src/components/Nav.jsx
  src/components/PopUp.jsx
  src/components/ToDoContainer.jsx
  src/components/atomic/Button.jsx
  src/components/atomic/Input.jsx
  src/components/atomic/SelectButton.jsx
  src/index.css
  src/main.jsx
  tailwind.config.cjs
Labels: hacktoberfest-accepted

#57 Adding an ID to a Task (uuid)
  package.json
  src/App.jsx
  src/components/Nav.jsx
  src/components/PopUp.jsx
  src/components/ToDoContainer.jsx
  src/components/Todo.jsx
  src/components/atomic/Input.jsx
  src/components/atomic/SelectButton.jsx
Labels: hacktoberfest-accepted

#55 readme updated
  README.md
Labels: hacktoberfest-accepted

#73 Bring pop up on top of everything
  src/components/PopUp.jsx
Labels: hacktoberfest-accepted

#67 Added responsiveness to the add task button and select button
  src/App.jsx
  src/components/Nav.jsx
  src/components/atomic/Button.jsx
  src/components/atomic/SelectButton.jsx
Labels: hacktoberfest-accepted

#79 Fix/components
  src/components/Nav.jsx
  src/components/PopUp.jsx
  src/components/ToDoContainer.jsx
  src/components/atomic/Button.jsx
  src/components/atomic/Input.jsx
  src/components/atomic/SelectButton.jsx
Labels: hacktoberfest-accepted

#49 Update main.jsx
  src/main.jsx
Labels: hacktoberfest-accepted

#82 Updated Figma Design
  public/design
Labels: design, hacktoberfest-accepted

#94 cursor pointer added to select button
  src/components/atomic/SelectButton.jsx
Labels: hacktoberfest-accepted

#90 Added filter and default value
  src/components/Nav.jsx
  src/components/PopUp.jsx
  src/components/ToDoContainer.jsx
  src/components/atomic/SelectButton.jsx
Labels: hacktoberfest-accepted

#96 Made so that enter submits task
  src/components/PopUp.jsx
  src/components/atomic/Input.jsx
Labels: hacktoberfest-accepted

#98 Formatting/prettier
  .eslintrc.cjs
  .github/ISSUE_TEMPLATE/bug_report.md
  .husky/pre-commit
  .lintstagedrc.cjs
  .prettierignore
  .prettierrc
  README.md
  package-lock.json
  package.json
  postcss.config.cjs
  src/App.jsx
  src/components/Header.jsx
  src/components/Nav.jsx
  src/components/PopUp.jsx
  src/components/ToDoContainer.jsx
  src/components/Todo.jsx
  src/components/atomic/Input.jsx
  src/components/atomic/SelectButton.jsx
  src/index.css
  src/main.jsx
  tailwind.config.cjs
  vite.config.js
Labels: hacktoberfest-accepted

#101 UX changes done
  src/components/Nav.jsx
  src/components/PopUp.jsx
  src/components/ToDoContainer.jsx
Labels: hacktoberfest-accepted

#121 Convert cjs files to js files and rely on default
  .eslintrc.js
  .lintstagedrc.js
  package.json
  postcss.config.js
  tailwind.config.js
Labels: hacktoberfest-accepted

#119 feat(UI): delete, change status, edit tasks
  .prettierignore
  package-lock.json
  package.json
  src/App.jsx
  src/components/Nav.jsx
  src/components/PopUp.jsx
  src/components/ToDoContainer.jsx
  src/components/Todo.jsx
  src/components/atomic/SelectButton.jsx
  tailwind.config.js
Labels: hacktoberfest-accepted

#95 Make coffee task a progressive web application
  dev-dist/registerSW.js
  dev-dist/sw.js
  dev-dist/workbox-3589c0c5.js
  index.html
  package-lock.json
  package.json
  public/android-chrome-192x192.png
  public/android-chrome-256x256.png
  public/android-chrome-384x384.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/maskable_icon.png
  vite.config.js
Labels: hacktoberfest-accepted

#130 Updated component Select and Readme. Close #125, Close #126
  README.md
  src/components/atomic/SelectButton.jsx
Labels: hacktoberfest

#128 Add new eslint rule which removes the need to have React in scope
  .eslintrc.js
  README.md
  src/App.jsx
  src/components/Header.jsx
  src/components/Nav.jsx
  src/components/PopUp.jsx
  src/components/ToDoContainer.jsx
  src/components/Todo.jsx
  src/components/atomic/Button.jsx
  src/components/atomic/Input.jsx
  src/components/atomic/SelectButton.jsx
  src/main.jsx
Labels: hacktoberfest-accepted

#107 added/updated UI for mobile version in figma
  src/assets/Delete Trash.svg
  src/assets/Success Check.svg
Labels: hacktoberfest-accepted

#145 Documentation modified
  README.md
  package-lock.json
Labels: hacktoberfest-accepted

#139 feat: add a description field to the todo
  src/components/PopUp.jsx
Labels: hacktoberfest-accepted

#150 Bug Fixed: Added task name validation
  package-lock.json
  src/components/PopUp.jsx
Labels: hacktoberfest-accepted

#142 burn: remove padding to match layout figma
  src/components/Nav.jsx
Labels: hacktoberfest-accepted

#148 fix the confirmation dialog
  .eslintrc.js
  .prettierrc
  README.md
  dev-dist/registerSW.js
  dev-dist/sw.js
  dev-dist/workbox-3589c0c5.js
  src/components/DeletionDialog.jsx
  src/components/ToDoContainer.jsx
  vite.config.js
Labels: hacktoberfest-accepted
